# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Picture', to='Authentication.User'))),
                ('upload_time', models.DateField(auto_now=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Picture', to='Authentication.User')),
            ],
        ),
    ]
