# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
