# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Webpages', '0002_auto_20161101_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio', models.FileField(null=True, upload_to='videos/')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Video', to='Authentication.User')),
            ],
        ),
    ]
