# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpages', '0005_auto_20161113_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='barrage',
            field=models.FileField(default=None, null=True, upload_to='barrages/'),
        ),
    ]
