# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20161119_1553'),
        ('Webpages', '0006_auto_20161113_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096)),
                ('create_time', models.TimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Comment', to='Authentication.User')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(default=0, upload_to='videos/cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='discription',
            field=models.TextField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video_Comment', to='Webpages.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Catagory_Video', to='Webpages.Catagory'),
            preserve_default=False,
        ),
    ]
