# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20161119_1553'),
        ('Webpages', '0007_auto_20161120_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('title', models.CharField(max_length=512)),
                ('cover', models.ImageField(upload_to='audios/cover/')),
                ('discription', models.TextField(max_length=2048)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('lyric', models.FileField(upload_to='audios/lyrics')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catagory_Audio', to='Webpages.Catagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Audio', to='Authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096)),
                ('create_time', models.TimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('like', models.IntegerField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio_Comment', to='Webpages.Audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AUser_Comment', to='Authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='Picture_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096)),
                ('create_time', models.TimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='img',
        ),
        migrations.AddField(
            model_name='picture',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Catagory_Picture', to='Webpages.Catagory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='cover',
            field=models.ImageField(default=2, upload_to='pictures/cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='discription',
            field=models.TextField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default=0, upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='video_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VUser_Comment', to='Authentication.User'),
        ),
        migrations.AddField(
            model_name='picture_comment',
            name='Picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Picture_Comment', to='Webpages.Picture'),
        ),
        migrations.AddField(
            model_name='picture_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PUser_Comment', to='Authentication.User'),
        ),
    ]
