# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpages', '0008_auto_20161124_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_comment',
            old_name='Picture',
            new_name='picture',
        ),
    ]
