# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20161202_1038'),
        ('Webpages', '0011_auto_20161202_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collect_Audio', to='Webpages.Audio')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collect_Picture', to='Webpages.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collect_User', to='Authentication.User')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collect_Video', to='Webpages.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislike_Audio', to='Webpages.Audio')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislike_Picture', to='Webpages.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dislike_User', to='Authentication.User')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislike_Video', to='Webpages.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Like_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_Audio', to='Webpages.Audio')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_Picture', to='Webpages.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like_User', to='Authentication.User')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_Video', to='Webpages.Video')),
            ],
        ),
    ]
