# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpages', '0012_collect_item_dislike_item_like_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_Items',
            new_name='Like_Item',
        ),
    ]
