# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpages', '0015_auto_20161212_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='mp3',
            field=models.FileField(blank=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='audio',
            name='wav',
            field=models.FileField(blank=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='video',
            name='flv',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='mp4',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='three_gp',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
