# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face1',
            field=models.ImageField(null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face2',
            field=models.ImageField(null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face3',
            field=models.ImageField(null=True, upload_to='faces/'),
        ),
    ]
