# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20161125_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discription',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
