# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20161125_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face4',
            field=models.ImageField(null=True, upload_to='user/faces/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face5',
            field=models.ImageField(null=True, upload_to='user/faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='user/avatars'),
        ),
    ]
