# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20161202_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face1',
            field=models.ImageField(blank=True, null=True, upload_to='user/faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face2',
            field=models.ImageField(blank=True, null=True, upload_to='user/faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face3',
            field=models.ImageField(blank=True, null=True, upload_to='user/faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face4',
            field=models.ImageField(blank=True, null=True, upload_to='user/faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face5',
            field=models.ImageField(blank=True, null=True, upload_to='user/faces/'),
        ),
    ]
