$(document).ready(function(){
	$("#Na_video").click(function(){
		document.getElementById("Content_video").style.visibility="visible";
		document.getElementById("Content_audio").style.visibility="hidden";
		document.getElementById("Content_image").style.visibility="hidden";
		document.getElementById("Content_user").style.visibility="hidden";
		document.getElementById("Na_video_img").src="images/search/_video_u61_mouseOver.png";
		document.getElementById("Na_audio_img").src="images/search/_video_u61.png";
		document.getElementById("Na_image_img").src="images/search/_video_u61.png";
		document.getElementById("Na_user_img").src="images/search/_video_u61.png";
	});
	$("#Na_audio").click(function(){
		document.getElementById("Content_video").style.visibility="hidden";
		document.getElementById("Content_audio").style.visibility="visible";
		document.getElementById("Content_image").style.visibility="hidden";
		document.getElementById("Content_user").style.visibility="hidden";
		document.getElementById("Na_video_img").src="images/search/_video_u61.png";
		document.getElementById("Na_audio_img").src="images/search/_video_u61_mouseOver.png";
		document.getElementById("Na_image_img").src="images/search/_video_u61.png";
		document.getElementById("Na_user_img").src="images/search/_video_u61.png";
	});
	$("#Na_image").click(function(){
		document.getElementById("Content_video").style.visibility="hidden";
		document.getElementById("Content_audio").style.visibility="hidden";
		document.getElementById("Content_image").style.visibility="visible";
		document.getElementById("Content_user").style.visibility="hidden";
		document.getElementById("Na_video_img").src="images/search/_video_u61.png";
		document.getElementById("Na_audio_img").src="images/search/_video_u61.png";
		document.getElementById("Na_image_img").src="images/search/_video_u61_mouseOver.png";
		document.getElementById("Na_user_img").src="images/search/_video_u61.png";
	});
	$("#Na_user").click(function(){
		document.getElementById("Content_video").style.visibility="hidden";
		document.getElementById("Content_audio").style.visibility="hidden";
		document.getElementById("Content_image").style.visibility="hidden";
		document.getElementById("Content_user").style.visibility="visible";
		document.getElementById("Na_video_img").src="images/search/_video_u61.png";
		document.getElementById("Na_audio_img").src="images/search/_video_u61.png";
		document.getElementById("Na_image_img").src="images/search/_video_u61.png";
		document.getElementById("Na_user_img").src="images/search/_video_u61_mouseOver.png";
	});
});